server:
  port: 8081
  mvc:
    view:
      prefix: /
      suffix: .html

spring:
  datasource:
    username: yourUserName
    password: yourPassWord
    url: yourURL
#    url: jdbc:mysql://localhost:3306/data?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
